use_frameworks!

platform :ios, '9.0'

target 'renxqNetwork_Example' do
  pod 'renxqNetwork', :path => '../'

  target 'renxqNetwork_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
